apps/basket/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("add/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<int:cart_item_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("", views.cart_detail, name="cart_detail"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls', namespace='users')),
    path('basket/', include('apps.basket.urls', namespace='cart')),
    path('products/', include('apps.product.urls', namespace='products')),
    path('', include('apps.my_shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart/add_to_cart.html
{% extends "base.html" %}

{% block content %}    
    {{ message }}

    <form method="post">
        {% csrf_token %}
{#        <input type="submit" value="Add to Cart">#}
    </form>
{% endblock %}

templates/cart/cart_ditail.html
{% extends "base.html" %}
{% block content %}

    {% if cart_items %}
        <table class="table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                    <tr>
                        <td>{{ item.product.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.product.amount }}{{ item.product.currency }}</td>
                        <td>{{ item.quantity }} * {{ item.product.amount }}</td>
                        <td><a href="{% url 'cart:remove_from_cart' item.id %}">Remove</a></td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3"></td>
                    <td>Total:</td>
                    <td>{{ total_price }}</td>
                </tr>
            </tfoot>
        </table>

{#        <a href="{% url 'checkout' %}" class="btn btn-primary">Checkout</a>#}
    {% else %}
        <p>Your shopping cart is empty.</p>
    {% endif %}
{% endblock %}

templates/cart/remove_from_cart.html
{% extends "base.html" %}
{% block content %}
   
    {{ message }}

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Remove from Cart">
        <a href="{% url 'cart:remove_from_cart' cart_item_id %}">Remove</a>
    </form>
{% endblock %}