apps/basket/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("add/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<int:cart_item_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("", views.cart_detail, name="cart_detail"),
]

apps/product/urls.py
from django.urls import path
from .views import ditail_view, add_product_view, update_product_view, delete_product_view, my_products_view

app_name = 'products'
urlpatterns = [
    path('ditail/<int:pk>/', ditail_view, name='ditail'),
    path('add_product/', add_product_view, name='add_product'),
    path('update/<int:pk>/', update_product_view, name='update'),
    path('delete/<int:pk>/', delete_product_view, name='delete'),
    path('my_products/', my_products_view, name='my_products'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls', namespace='users')),
    path('basket/', include('apps.basket.urls', namespace='cart')),
    path('products/', include('apps.product.urls', namespace='products')),
    path('', include('apps.my_shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from helpers.upload_files import upload_product_image
from helpers.choices import MoneyTypeChoices, SizeTypeChoices, CategoriesTypeChoices


class Product(models.Model):
    name = models.CharField(max_length=255)
    model = models.CharField(max_length=255, null=True, blank=True)
    count = models.DecimalField(max_digits=10, decimal_places=0)
    amount = models.DecimalField(max_digits=10, decimal_places=1)
    currency = models.CharField(max_length=25, choices=MoneyTypeChoices.choices)
    description = models.TextField(null=True, blank=True)
    size = models.CharField(max_length=50, choices=SizeTypeChoices.choices, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)
    rate = models.DecimalField(max_digits=2, decimal_places=1)
    photo = models.ImageField(upload_to=upload_product_image)
    video = models.FileField(upload_to='videos/', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    categories = models.ForeignKey('Categories', on_delete=models.CASCADE)
    # character = models.ForeignKey('Character', on_delete=models.CASCADE, verbose_name='Characteristics')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ditail', kwargs={'pk': self.pk})


class Categories(models.Model):
    name = models.CharField(max_length=255, choices=CategoriesTypeChoices.choices)

    def __str__(self):
        return self.name


# class Character(models.Model):
#     other = models.CharField(max_length=155, null=True, blank=True)
#     origin = models.CharField(max_length=200)
#     certification = models.CharField(max_length=155, null=True, blank=True)
#     brand = models.ForeignKey('Brand', on_delete=models.CASCADE, null=True, blank=True)
#
#     def __str__(self):
#         return f'{self.brand} {self.origin}'


# class Brand(models.Model):
#     name = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.name

apps/product/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'model', 'amount', 'currency', 'count', 'description', 'size',
                  'color', 'rate', 'photo', 'video', 'categories')

apps/product/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Product, Categories
from .forms import ProductForm
from django.views.generic import UpdateView


def add_product_view(request):
    if request.method == 'POST':
        # initial_form = {'owner': user}
        form = ProductForm(request.POST, request.FILES)
        user = request.user
        if form.is_valid():
            # data = form.cleaned_data
            # print(type(form.cleaned_data))
            # data['owner_id'] = user.id
            # Product.objects.create(**data)
            instance = form.save(commit=False)
            instance.owner = user
            instance.save()
            return redirect('home')
    form = ProductForm()

    return render(request, 'product/add_product.html', context={'form': form, 'title': 'Add Page'})


def ditail_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    all_cat_products = Product.objects.filter(categories=product.categories)
    paginator = Paginator(all_cat_products, 4)
    page_number = request.GET.get("page")
    cat_list = paginator.get_page(page_number)
    price_off = product.amount - (product.amount * 20) // 100

    if request.method == "POST":
        messages.success(request, f"{product.name} added to your cart.")
        return redirect("cart:add_to_cart", product_id=product.id)

    context = {
        'product': product,
        'title': f'{product.name} Ditail',
        'price_off': price_off,
        'cat_list': cat_list,
    }
    return render(request, 'product/ditail.html', context=context)


def update_product_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    form = ProductForm(instance=product)
    if request.method == 'POST' and request.user.profile.category == 'SALESMAN':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, f'Product {product.name} updated successfully')
            return redirect('home')
    return render(request, 'product/update.html', context={'form': form, 'pk': product.pk,
                                                           'title': f'UPDATE{product.name}'})


# class UpdateProduct(UpdateView):


def delete_product_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        return redirect('home')
    return render(request, 'product/delete.html', context={'pk': product.pk, 'title': f'DELETE{product.name}'})


def my_products_view(request):
    my_products = []
    my_cats = []
    if request.user.is_authenticated:
        user = request.user
        my_products = Product.objects.filter(owner=user)
        my_cats = Categories.objects.filter(product__owner=user)
    return render(request, 'product/my_products.html', context={'my_products': my_products, 'title': 'my_products',
                                                                'my_cats': my_cats})

templates/product/add_product.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid px-1 py-5 mx-auto">
        <div class="row d-flex justify-content-center">
            <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
                <h3>Fill necessary fields</h3>
                <p class="blue-text">Just fill a necessary fields<br> if you want to add new product.</p>
                <div class="card">
                    <h5 class="text-center mb-4">Powering world-class companies</h5>
                    <form class="form-card" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row justify-content-center text-left">
                            <div class="form-group col-sm-6 flex-column d-flex">
                                {{ form.as_table }}
{#                                {{ form.as_p }}#}
                                <button type="submit" class="btn btn-success">ADD</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/product/category_products.html
{% extends 'base.html' %}
{% block content %}
{% for p in cat %}
    {{ p }}
    {% endfor %}

{% endblock %}

templates/product/delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <p>Are you sure you want to delete this product</p>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">DELETE</button>
        </form>
        <button class="btn btn-primary" type="submit"><a href="{% url 'products:delete' pk %}">Cancel</a></button>
    </div>
{% endblock %}

templates/product/ditail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/ditail_1.css' %}" rel="stylesheet">

    <style>
        .text-bold {
            font-weight: 800;
        }

        text-color {
            color: #0093c4;
        }

        /* Main image - left */
        .main-img img {
            width: 100%;
        }

        /* Preview images */
        .previews img {
            width: 100%;
            height: 140px;
        }

        .main-description .category {
            text-transform: uppercase;
            color: #0093c4;
        }

        .main-description .product-title {
            font-size: 2.5rem;
        }

        .old-price-discount {
            font-weight: 600;
        }

        .new-price {
            font-size: 2rem;
        }

        .details-title {
            text-transform: uppercase;
            font-weight: 600;
            font-size: 1.2rem;
            color: #757575;
        }

        .buttons .block {
            margin-right: 5px;
        }

        .quantity input {
            border-radius: 0;
            height: 40px;

        }


        .custom-btn {
            text-transform: capitalize;
            background-color: #0093c4;
            color: white;
            width: 150px;
            height: 40px;
            border-radius: 0;
        }

        .custom-btn:hover {
            background-color: #0093c4 !important;
            font-size: 18px;
            color: white !important;
        }

        .similar-product img {
            height: 400px;
        }

        .similar-product {
            text-align: left;
        }

        .similar-product .title {
            margin: 17px 0px 4px 0px;
        }

        .similar-product .price {
            font-weight: bold;
        }


        /* Small devices (landscape phones, less than 768px) */
        @media (max-width: 767.98px) {

            /* Make preview images responsive  */
            .previews img {
                width: 100%;
                height: auto;
            }

        }
    </style>


    <div class="container my-5">
        <div class="row">
            <div class="col-md-5">
                <div class="main-img">
                    <img class="img-fluid" src="{{ product.photo.url }}" alt="ProductS">
                    <div class="row my-3 previews">
                        {% if product.video %}
                            <iframe src="{{ product.video }}" title="Vimeo video" allowfullscreen></iframe>
                        {% else %}
                            <iframe src="https://player.vimeo.com/video/137857207" title="Vimeo video"
                                    allowfullscreen></iframe>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="main-description px-2">
                    <div class="category text-bold">
                        Category: {{ product.categories.name }}
                    </div>
                    <div class="product-title text-bold my-3">
                        {{ product.name }} {{ product.model }}
                    </div>


                    <div class="price-area my-4">
                        <p class="old-price mb-1">
                            <del>{{ product.amount }} {{ product.currency }}</del>
                            <span class="old-price-discount text-danger">(20% off)</span></p>
                        <p class="new-price text-bold mb-1">{{ price_off }}</p>
                        <p class="text-secondary mb-1">(Additional tax may apply on checkout)</p>

                    </div>


                    <div class="buttons d-flex my-5">
                        <div class="block">
                            <a href="{% url 'cart:add_to_cart' product.pk %}" class="shadow btn custom-btn ">Basket</a>
                        </div>
                        <div class="block">
                            <button class="shadow btn custom-btn">Buy Now</button><br>
                        </div>
                        <div class="block">

                            {% if request.user.profile.category == 'SALESMAN' and product.owner == request.user %}

                                <button class="shadow btn custom-btn"><a
                                        href="{% url 'products:update' product.pk %}">UPDATE</a></button>
                                <button class="shadow btn custom-btn"><a
                                        href="{% url 'products:delete' product.pk %}">DELETE</a></button>
                            {% endif %}
                        </div>

                        <div class="block quantity">
                            <input type="number" class="form-control" id="cart_quantity" value="1" min="0" max="5"
                                   placeholder="Enter email" name="cart_quantity">
                        </div>
                    </div>


                </div>

                <div class="product-details my-4">
                    {% if product.color %}
                        <p class="details-title text-color mb-2">Color</p>
                        <ul>
                            <div class="attr" style="width:25px;background:{{ product.color }};"></div>

                        </ul>
                    {% endif %}
                    {% if product.size %}
                        <p class="details-title text-color mb-2">Size</p>
                        <li>{{ product.size }}</li>
                        </div>
                    {% endif %}

                <div class="product-details my-4">
                    <p class="details-title text-color mb-2">Rate</p>
                    <ul>

                        <li>{{ product.rate }}</li>
                    </ul>
                </div>

                <div class="product-details my-4">
                    <p class="details-title text-color mb-1">Product Details</p>
                    <p class="details-title text-color mb-1"><small>Description</small></p>
                    {% autoescape on %}
                        <p class="description"><small>{{ product.description | linebreaks|truncatewords:20 }}</small>
                        </p>
                    {% endautoescape %}
                </div>
            </div>

        </div>
    </div>

    <div class="container similar-products my-4">
        <hr>
        <p class="display-5">Similar Products</p>
        <div class="row">
            {% for p in cat_list %}
                <div class="col-md-3">
                    <div class="similar-product">
                        <a href="{% url 'products:ditail' p.pk %}"><img class="w-100" src="{{ p.photo.url }}" alt="Preview"></a>
                        <p class="title">{{ p.name }}</p>
                        <p class="price">{{ p.amount }} {{ p.currency }}</p>

                    </div>

                </div>
            {% endfor %}
        {% include 'layouts/pagination.html' with page_obj=cat_list %}
        </div>
    </div>






    <div class="footer mt-5">
        <div class="container1">
            <footer class="py-3 my-4">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item"><a href="{% url 'home' %}" class="nav-link px-2 text-muted">Home</a></li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
                </ul>
                <p class="text-center text-muted">© 2022 Company, Inc</p>
            </footer>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

templates/product/my_products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% for my_cat in my_cats %}
        <div class="fashion_section">
        <div id="main_slider" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container">
                <h1 class="fashion_taital">{{ my_cat.name }}</h1>
                <br>
                <div class="fashion_section_2">
                    <div class="row">
                        {% for product in my_products %}
                            {% if product.categories.name == my_cat.name %}
                                <div class="col-lg-4 col-sm-4">
                                    <div class="box_main">
                                        <h4 class="shirt_text">{{ product.name }} {{ product.model }}</h4>
                                        <p class="price_text">Price <span style="color: #262626;">{{ product.amount }}
                                            {{ product.currency }}</span></p>
                                        <div class="tshirt_img"><img src="{{ product.photo.url }}"></div>
                                        <div class="btn_main">
                                            <div class="buy_bt"><a href="#">Buy Now</a></div>
                                            <div class="seemore_bt"><a href="{% url 'products:ditail' product.pk %}">See More</a></div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <div>
        <div>
            <div class="loader_main">
                <div class="loader"></div>
            </div>
        </div>
    </div>
    <!-- jewellery  section end -->
{% endblock %}

templates/product/update.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid px-1 py-5 mx-auto">
        <div class="row d-flex justify-content-center">
            <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
                <h3>Fill necessary fields</h3>
                <p class="blue-text">Just answer a few questions<br> so that we can personalize the right experience for
                    you.</p>
                <div class="card">
                    <h5 class="text-center mb-4">Powering world-class companies</h5>
                    <form class="form-card" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row justify-content-center text-left">
                            <div class="form-group col-sm-6 flex-column d-flex">
                                {{ form.as_table }}
{#                                {{ form.as_p }}#}
                                <button type="submit" class="btn btn-success">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}