apps/product/urls.py
from django.urls import path
from .views import ditail_view, add_product_view, update_product_view, delete_product_view, my_products_view

app_name = 'products'
urlpatterns = [
    path('ditail/<int:pk>/', ditail_view, name='ditail'),
    path('add_product/', add_product_view, name='add_product'),
    path('update/<int:pk>/', update_product_view, name='update'),
    path('delete/<int:pk>/', delete_product_view, name='delete'),
    path('my_products/', my_products_view, name='my_products'),
]

apps/users/urls.py
from django.urls import path
from .views import register_user, login_view, logout_view, profile_view, UserUpdateView, delete_user_view

app_name = 'users'
urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('update/<int:pk>', UserUpdateView.as_view(), name='update'),
    path('delete/', delete_user_view, name='delete'),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls', namespace='users')),
    path('basket/', include('apps.basket.urls', namespace='cart')),
    path('products/', include('apps.product.urls', namespace='products')),
    path('', include('apps.my_shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save
from django.dispatch import receiver
from helpers.choices import CategoryTypeChoices


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True)
    photo = models.ImageField(upload_to='profile_photo', blank=True)
    category = models.CharField(max_length=50, choices=CategoryTypeChoices.choices)
    phone = PhoneNumberField(blank=True, help_text='Phone number')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile_model(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField
from helpers.choices import CategoryTypeChoices


class UserForm(UserCreationForm):
    phone = PhoneNumberField()
    category = forms.ChoiceField(choices=CategoryTypeChoices.choices, label='Choice field')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'username',
                  'category', 'password1', 'password2')

        # widgets = {
        #     'first_name': forms.TextInput(attrs={'class': 'form-input'}),
        #     'email': forms.EmailInput(attrs={'class': 'form-input'}),
        #     'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
        #     'password2': forms.PasswordInput(attrs={'class': 'form-input'}),
        # }


class UserUpdateForm(forms.ModelForm):
    phone = PhoneNumberField(required=False)
    photo = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username',
                  'phone', 'photo')

apps/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView, DeleteView

from helpers.mixins import LoginRequiredMixin
from .forms import UserForm, UserUpdateForm
from .models import Profile
from ..product.models import Product


def register_user(request):
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            phone = form.cleaned_data.get('phone')
            category = form.cleaned_data.get('category')
            user = form.save()
            user.profile.phone = phone
            user.profile.category = category
            user.profile.save()
            messages.success(request, f'User with {user.username} username created successfully')
            return redirect('home')
    return render(request, 'users/register.html', context={'form': form, 'title': 'REGISTER PAGE'})


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user=user)
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            return redirect('home')
    return render(request, 'users/login.html', {'title': 'LOGIN PAGE'})


@login_required
def logout_view(request):
    logout(request)
    messages.info(request, 'Successfully loging out')
    return redirect('home')


def profile_view(request):
    if request.user.is_authenticated:
        user = request.user
        product = Product.objects.filter(owner=user)
        profile = Profile.objects.filter(user=user)
    else:
        return redirect('login')
    return render(request, 'users/profile.html', context={'profile': profile, 'title': 'Profile Page',
                                                          'product': product})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/update.html'

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_form_kwargs(self):
        user = self.get_object()
        kwargs = super().get_form_kwargs()
        kwargs.update({'initial': {'phone': user.profile.phone,
                                   'photo': user.profile.photo}})
        return kwargs

    def form_valid(self, form):
        user = self.get_object()
        phone = form.cleaned_data.get('phone')
        photo = form.cleaned_data.get('photo')
        user.profile.phone = phone
        user.profile.photo = photo
        user.profile.save()
        return super().form_valid(form)


# class UserDeleteView(DeleteView):
#     model = User
#     success_url = '/'
#     template_name = 'users/delete.html'


def delete_user_view(request):
    user = request.user
    if request.method == 'POST' and request.user == user:
        user.delete()
        return redirect('home')
    return render(request, 'users/delete.html', context={'title': f'DELETE{user.username}'})

templates/users/delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want  to delete your account?</p>
        <button class='btn btn-danger' type="submit">Delete</button>
    </form>
    <a href="{% url 'users:profile' %}">Cancel</a>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="mb-md-5 mt-md-4 pb-5">

                                    <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                                    <p class="text-white-50 mb-5">Please enter your login and password!</p>

                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="username" id="typeEmailX" class="form-control form-control-lg"
                                               placeholder="Enter a valid username " />
                                        <label class="form-label" for="typeEmailX">Username</label>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <input type="password" name="password" id="typePasswordX" class="form-control form-control-lg"
                                        placeholder="Enter password" />
                                        <label class="form-label" for="typePasswordX">Password</label>
                                    </div>

                                    <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot
                                        password?</a>
                                    </p>

                                    <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>

                                    <div class="d-flex justify-content-center text-center mt-4 pt-1">
                                        <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                                        <a href="#!" class="text-white"><i
                                                class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                                        <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                                    </div>

                                </div>

                                <div>
                                    <p class="mb-0">Don't have an account? <a href="{% url 'users:register' %}"
                                                                              class="text-white-50 fw-bold">Sign
                                        Up</a>
                                    </p>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!------ Include the above in your HEAD tag ---------->
{#    {% if request.user.profile.category == 'SALESMAN' %}#}
        <link href="{% static 'css/profile.css' %}" rel="stylesheet" id="bootstrap-css">
        <div class="container emp-profile">
{#            <form>#}
                {% for p in profile %}
                    <div class="row">
                        <div class="col-md-4">
                            <div class="profile-img">
                                {% if p.photo %}
                                    <img src="{{ p.photo.url }}"
                                         alt=""/>
                                {% else %}
                                    <img src="{% static 'images/images (1).jpg' %}"
                                         alt=""/>
                                {% endif %}
{#                                <div class="file btn btn-lg btn-primary">#}
{#                                    <a href="#">Change Photo</a>#}
{#                                    <input type="file" name="file"/>#}
{#                                </div>#}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="profile-head">
                                <h1>
                                    {{ p.user.username }}
                                </h1>
                                <h6>
                                    {{ p.user.profile.category }}
                                </h6>
                                <ul class="nav nav-tabs" id="myTab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home"
                                           role="tab"
                                           aria-controls="home" aria-selected="true">About</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile"
                                           role="tab"
                                           aria-controls="profile" aria-selected="false">Timeline</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <a href="{% url 'users:update' request.user.pk%}"><input type="button" class="profile-edit-btn" name="btnAddMore" value="UPDATE"/></a>
                            <a href="{% url 'users:delete'%}"><input type="button" class="profile-edit-btn" name="btnAddMore" value="DELETE"/></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="profile-work">
                            {% if request.user.profile.category == 'SALESMAN' %}
                            <h3>Products</h3>
                                {% for p in product %}
                                <a href="{% url 'products:ditail' p.pk %}">{{ p.name }} {{ p.model }} - {{ p.count }} pcs</a><br/>
                                    {% endfor %}
                                {% else %}
                                <h3>Your Orders</h3>

                            {% endif %}
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="tab-content profile-tab" id="myTabContent">
                                <div class="tab-pane fade show active" id="home" role="tabpanel"
                                     aria-labelledby="home-tab">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>User</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>{{ p.user.username }}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>First Name</label>
                                        </div>
                                        <div class="col-md-6">
                                            {% if p.user.first_name %}
                                                <p>{{ p.user.first_name }}</p>
                                            {% else %}
                                                <p>Fill in the field</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Last Name</label>
                                        </div>
                                        <div class="col-md-6">
                                            {% if p.user.last_name %}
                                                <p>{{ p.user.last_name }}</p>
                                            {% else %}
                                                <p>Fill in the field</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Phone</label>
                                        </div>
                                        <div class="col-md-6">
                                            {% if p.phone %}
                                                <p>{{ p.phone }}</p>
                                            {% else %}
                                                <p>Fill in the field</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Email</label>
                                        </div>
                                        <div class="col-md-6">
                                            {% if p.user.email %}
                                                <p>{{ p.user.email }}</p>
                                            {% else %}
                                                <p>Fill in the field</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Login Time</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>{{ p.user.last_login }}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Hourly Rate</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>10$/hr</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Total Projects</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>230</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>English Level</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>Expert</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Availability</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>6 months</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <label>Your Bio</label><br/>
                                            <p>Your detail description</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
{#            </form>#}
        </div>


{#    {% else %}#}
{#            <link href="{% static 'css/client_profile.css' %}" rel="stylesheet">#}
{#            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">#}
{#            <link href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">#}

{#    {% endif %}#}

{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>#}
{#    <script src="{% static 'js/profile.js' %}"></script>#}

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="h-100 bg-dark">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                    <div class="card card-registration my-4">

                        <form method="post">
                        {% csrf_token %}
                            <div class="row g-0">
                                <div class="col-xl-6 d-none d-xl-block">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img4.webp"
                                         alt="Sample photo" class="img-fluid"
                                         style="border-top-left-radius: .20rem; border-bottom-left-radius: .20rem;"/>
                                </div>
                                <div class="col-xl-6">
                                    <div class="card-body p-md-5 text-black">
                                        <h3 class="mb-5 text-uppercase">Registration form</h3>

                                        <div class="row">

                                            {% for f in form %}

                                                <div class="col-md-6 mb-4">

                                                    <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
                                                </div>
                                                <div class="form-error">{{ f.errors }}</div>
                                            {% endfor %}


                                            <div class="d-flex justify-content-end pt-3">
                                                <button type="submit" class="btn btn-warning btn-lg ms-2">Submit form
                                                </button>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/users/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="h-100 bg-dark">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                    <div class="card card-registration my-4">

                        <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="row g-0">
                                <div class="col-xl-6 d-none d-xl-block">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img4.webp"
                                         alt="Sample photo" class="img-fluid"
                                         style="border-top-left-radius: .20rem; border-bottom-left-radius: .20rem;"/>
                                </div>
                                <div class="col-xl-6">
                                    <div class="card-body p-md-5 text-black">
                                        <h3 class="mb-5 text-uppercase">Registration form</h3>

                                        <div class="row">

                                            {% for f in  %}

                                                <div class="col-md-6 mb-4">

                                                    <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}
                                                    </label>{{ f }}
                                                </div>
                                                <div class="form-error">{{ f.errors }}</div>
                                            {% endfor %}


                                            <div class="d-flex justify-content-end pt-3">
                                                <button type="submit" class="btn btn-warning btn-lg ms-2">Update form
                                                </button>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}